version: "3"
services:
  php:
    image: php:8.2-apache
    network_mode: "host"
    volumes:
      - ../www:/var/www/html
    environment:
      - KUBERNETES_NODE_NAME=test-node
      - KUBERNETES_SERVICE_PORT_HTTPS=443
      - KUBERNETES_SERVICE_PORT=443
      - HOSTNAME=test-nginx-6c68796bb-b9djb
      - PWD=/
      - PKG_RELEASE=1~bullseye
      - HOME=/root
      - KUBERNETES_PORT_443_TCP=tcp://10.112.0.1:443
      - TEST_NGINX_SRV_PORT_80_TCP_PORT=80
      - TEST_NGINX_SRV_PORT_80_TCP_ADDR=10.117.191.180
      - NJS_VERSION=0.7.12
      - TERM=xterm
      - TEST_NGINX_SRV_SERVICE_PORT=80
      - SHLVL=1
      - TEST_NGINX_SRV_SERVICE_HOST=10.117.191.180
      - KUBERNETES_PORT_443_TCP_PROTO=tcp
      - KUBERNETES_PORT_443_TCP_ADDR=10.112.0.1
      - TEST_NGINX_SRV_PORT_80_TCP_PROTO=tcp
      - KUBERNETES_SERVICE_HOST=10.112.0.1
      - KUBERNETES_PORT=tcp://10.112.0.1:443
      - KUBERNETES_PORT_443_TCP_PORT=443
      - TEST_NGINX_SRV_PORT=tcp://10.117.191.180:80
      - TEST_NGINX_SRV_PORT_80_TCP=tcp://10.117.191.180:80
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - NGINX_VERSION=1.24.0
