version: "3"
services:
  php:
    image: php:8.2-apache
    network_mode: "host"
    volumes:
      - ../www:/var/www/html
    environment:
      - KUBERNETES_NODE_NAME=test-node
      - HOSTNAME=test-nginx-6c68796bb-b9djb
